#!/usr/bin/env bash
# transfers a file from our client to a server
# path_to_file="$1"
# ip="$2"
# username="$3"
# path_to_ssh_key="$4"
# scp must transfer the file to the user home directory ~/
# Strict host key checking must be disabled when using scp

# Check if less than 3 parameters are provided

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	 scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
