#!/usr/bin/env bash
# Install nginx web server on web-01
# should be listening on port 80
# Serve a page that would return a Hello World string

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" |sudo tee /var/www/html/index.html
sudo service nginx start
