#!/usr/bin/env bash
# installs nginx server

sudo apt update
sudo apt install -y nginx
echo "Hello World" > /var/www/html/index.html
sudo sed -i "53s/.*/location \/redirect_me {\n\treturn 301 http:\/\/github.com\/\;\n}/" /etc/nginx/sites-available/default
sudo service nginx restart
