#!/usr/bin/env bash
# This script pings an IP address passed as an argument.
# Accepts a string as an argument and pings the IP 5 times
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed

if [ "$#" -eq 0 ];
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
