#!/usr/bin/env bash
# Configure Nginx, restart the service, and ensure a clean restart

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
rm /run/nginx.pid
