#!/usr/bin/env bash
# This script displays; "To infinity and beyond" indefinetly
# With a sleep 2 in between each iteration
# Displays "I am invincible!!!" when receiving a SIGTERM signal

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
