#!/usr/bin/env bash
# Displays the contents of /etc/passwd
# Using while loop + IFS

fname="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7

do

    printf "The user %s is part of the %s gang, lives in %s and rides " "$f1" "$f4" "$f6"

    printf "%s. %s's place is protected by the passcode %s, more info about the user here:" "$f7" "$f3" "$f2"

    printf " %s" "$f5"

    printf "\n"

done < "$fname"
