#!/usr/bin/env bash
# This script displays the content of the current directory
# In a list format, without hidden files
# Must use a for loop

list=$(ls)

for i in $list
do
	echo "$i" | cut -d '-' -f2
done
