#!/usr/bin/env bash
# This scripts configures an ubuntu server with;
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
cp /etc/hosts hosts.new
sed -i s/127.*$/127.0.0.2\\tlocalhost\\n8.8.8.8\\tfacebook.com/g hosts.new
